### ISSUE TITLE
 Unhandled exception rendering component: Vditor is not defined

### ISSUE THREAD

**Issue by zhoudali87** [ant-design-blazor/vditor-blazor#9]
Microsoft.JSInterop.JSException: Vditor is not defined
      ReferenceError: Vditor is not defined
          at Object.preview (https://localhost:5001/_content/Vditor/vditor-blazor.js:67:5)
          at https://localhost:5001/_framework/blazor.server.js:1:70055
          at new Promise (<anonymous>)
          at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:70021)
          at https://localhost:5001/_framework/blazor.server.js:1:26303
          at Array.forEach (<anonymous>)
          at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:26273)
          at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:24211)
          at e.connection.onreceive (https://localhost:5001/_framework/blazor.server.js:1:17296)
          at WebSocket.i.onmessage (https://localhost:5001/_framework/blazor.server.js:1:46513)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Vditor.Preview.SetPreview() in /Users/zhoudali/Downloads/vditor-blazor-master/src/Vditor/Components/Preview.razor.cs:line 76
         at Vditor.Preview.OnAfterRenderAsync(Boolean firstRender) in /Users/zhoudali/Downloads/vditor-blazor-master/src/Vditor/Components/Preview.razor.cs:line 68
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by ElderJames** [comment]
Please add the vditor links in _Host.cshtml

```
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vditor@3.4.7/dist/index.css" />
    <script src="https://cdn.jsdelivr.net/npm/vditor@3.4.7/dist/index.min.js" defer></script>
    <script src="_content/Vditor/vditor-blazor.js"></script>
```
